import GameSwiftEngine

final class MainNode: SceneNode {
    var player: PlayerNode?

    override init() {
        super.init()
        addObject()
    }

    private func addObject() {
        let player = PlayerNode()
        scene?.mainCamera = player.camera
        self.player = player
        player.move(to: .init(-9.915023, 0.0, -1.8851681))
        player.rotate(to: .pi / 2, axis: .init(0, 1, 0))
        addSubnode(player)

        let light = LightNode()
        light.angle = .pi / 8
        light.attenuationAngle = .pi / 16
        light.power = 3
        light.color = .one
        light.move(to: .init(-7, -0.33333334, -10))
        light.rotate(to: -.pi, axis: .init(0, 1, 0))
        light.isShadow = true
        // self.addSubnode(light)

        let level = LevelNode(text: testMap)
        level.rotate(to: .pi, axis: .init(x: 0, y: 1, z: 0))
        addSubnode(level)
    }
}

//let testMap = """
//eeeeeeeeeeeeeeee
//eeeeeeeeeeeeeeee
//eeeeeeeeeeeeeeee
//eeeeeeweeeeeeeee
//eeeeeeeeeeeeeeee
//eeeeeeeeeeeeeeee
//eeeeeeeeeeeeeeee
//"""

let testMap =
"""
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeeeeeeeweeweweeeeeweweweweeweeeeweeeeeeeeeeewweeeeeewwwwwwwewewwewwwweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweweweweweeweeeeweeeeeeeeeeweeewweewewweeweweweeewwewewwwweweeeeeeeeeewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwweeeeeeeweeewweeweewewewewewwewwweeeeeeweeweeeweewewewweeeeewewewewweeeeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwewweweweeeweeeeweweeweweeeeeeeewweweweweweeewewweeeeweeeewweweeweweeewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeeeeeeeweeweweweweweeeewweweweeeweeweeeeewweeeeewewewewewwweweeeewewweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwewewewweewewweweeeweewweeeeeeewweeweeewewewwewewewweeeeweweweeweweeeewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeeweweeweweweeeweeewweeweweweweweewweeeeeeeeeeeeewweweeweeewewewewewwwewwweewwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeweeeeeweeeeewweweweweweeweeeeeewewewwewewwewewweweeeeewewweeeeeeeeeeweeeeeewwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeewewewewewewwweeeweeweweweweweeeeeeeeweeeweeewewwewweeeeewwewewewweeewewewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwewweweeeeeeweeeweweweweeeeewweeeweweweweeeweeweweeeeeewwewewweewwewwweweweeeeewwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeeeewwewweweweeweeeeeweweeewweeeeeewewweeweeeeewewewewewweeeweeewwewweeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwewewweeeeeeeeeeewewewweweeeweeeeweweweeewewewweweweeweeeeeweweweweeweeewweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeweewewweweweweeeeeeeeewwewewewewewewweweeweeeweewewweweeweeeweeweeweeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeweeeeewweeewwewewweweeeeeeeeeeeeeeeweweweweweweeeeeeewwewewewewewewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeweewewewwewweeeeeweeeeewwewewweweweweeeeeeeeeeeeeweweweeeeeeweweeeeeeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeweweeeeeweeweweewwewweweweeweeeeeeewewewweweweweeewewweweweeeewewewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeweeeeweweewweeeeweweeeeeeeeweeweweweeeeeeeeeeewweweeeeeeeeeeweweeeweeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwweeweweewweweeweweweeweweweweeeweeeweewewewweweweeeewwewwewweweeeeweeweweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeweeeweeeweeeeweeeewwweeeweeweeeweeeweeeeeeeeweeweweeweweeeeeeweweeweewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeweweewewwewewewweewewwewwewewweewewewewweweeweweeweweewwewewweewewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwewweeeeweeweeeeeeeweweeeewweeeeeweeweeeeeweeweweeeeeweeeeweeeeeeeewweeweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeeweweewweweweweeeeewweeewewweeeweewewweewweewewewewewewwewwewewweeweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweweeweeweeeeeeweeweweeewwewweewewwweweeeeweeewweeeweeeweeeeeewweweweewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeweweewwewewewwewweweweweeweeewwweewewewwewwewewewweewewwewweeeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwweeeewweeweweewweeeeeeeeeweeeweeeweeweweeeeeeweweeeweeeewewewweeeweweeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweweewewweweeewwewewweweweweeweeeweeeewewweeeeeweeewewweeeeeeweewwewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeweeeeeeewewweeeweeeeeeeewweeweeewwewewweweweewwewweeewewweewweeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweweeweweweeeeeeweewwewweweeweweewewweeeeeeweewweweeeeweeweeeweeweweeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeewewweewweweeweweeeeeewwewwweeeeeeweweeeweweeeweweeweeeweeeweeeewweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeweeeeeweeeeweweweweeweweeeeweweewweweewweweeweweeewewewweweweweweewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeeweweewweweeeeeeeeewewweweeeweeeeeeweeeeeeeeeeweweweeeeeeweeeeeweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwewweweeweweeeewweweweeeeeeeewweeeweeewweweweweweweeeeewweweweeweweeeweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwewweeweeeeewwewweeeeweweweweeeeweeweeeeeewewweeeeeweweeeeeweeweewewweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeeeweweweweeeeeewwewewewweweweweweweweweeeweewewweeewewweeweewweeewewewwwwewwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweewweeeewewwewewewewweweeeeeeeeweeeeeweweeweeewweeweweeeeweweweeeewweeeeeeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweewweweweeeeeeeeeeeeweeewwewewweeweweeeeweewewwewweeewweweeeeeewweeeewewewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeeeeeeewweeewewewweeweweweeeeweeeweweweweeeeeeeeeweeeeewewwewweweweewwwewewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwweweweweeweeeeweeweeweeeeweweweweweeeweeeewwewewweeeweweeeeeeweeweeewewweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeeweeeeweeweweweeewewewweweweeeewweweweweeweeeeeeweewwewewweeeweeweeeeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweewewweweeeeweeeeeweeeeeeeeeeeeweweeeeeeeeweeweweweweweeweeeeeweeewwewewweewewwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeeeweewweewweweeweweweweweweweweweweweweeeeweweeeeeweeeweweewweeeeeeeeweeeeewwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeweweeeweeewwweweweeeweeeeeweweeeeeeeeeweeweeeeewwewewweweeewweewwewewweewewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeeeweweweweweeeewwewweweweeeewewewewewwweweweeweweweeeeeeweeweeweeweeeweeeeewwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeweweeweeeeeeewweeeeweeeeeeweweeeeeeeewweeeeeewweeeeewweweeeweeeewweeweeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeweeweewewewweeewweeweweweweewewwewweeeeweweweewweweeeewwewewewweweweweweeewwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeweeweweewewewewweeeweewweeeeweeweeeeeweeewweweweewwewweeeeeeeeeeeeeeeeeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwweeweweeeweeeeeeewweweweeeweweeeweeweweeeeeeeeeeeeweeeeeewewwewweweweweweeeeeeeeewwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeeewweeewwwewwweeeewwewwewweweweweweeewewewewweewwewweeeeeeeweeeeweeeewwewewewwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweweweeeweewwwewewewewwweeeeweeeeeeeeeeweeeeeeewweeeweewewweweeeweweweweweeeeeewwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeeeewewwwwweeeeeeeeewwwwewweewewwewwewwwewweweeewweeewweweeeeweeeeeewweewewewwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwewewweewwwwwwewwwewewewweweeewwweeeeeewweeeeweeweeeweweeweewweeewewweeeewweeewwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweeeweewewwwwwwwwwwweeeeeeewewwweeweweweeeweweeweeweweeeweeeweeeweweeeewwewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweweeewwwwwwwwwwwwweeewwwweeeewwweeeeeeeweeweeweeweewwewewewewewwweewwewweeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwweewewwwwwwwwwwwwwwwwwwwwwewwweeeeweweweweweweewewweeweeeeeeeeeeweweeeeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwweeewwwwwwwwwwwwwwwwwwwwwwwwwewweeeeweeweeeeweeeeewwewwewewewweeeewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweweweeweewweewweweeeeweweeeeweweweeweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwewweeeeeweeweeweweweeweweeeewweeeeewweeweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewwewwewwewweeeeewweeeeweweeeewewewweweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweweweeewweeewwwwweweweeeweweeeewwewewweeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweeeeeeeweewwwwwwwwwewweewewewwewewweewweeweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweweweweweeweewwwwwwwwewwweeeewewweeeeewweweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewewweeweweweeeeewwwwwweeeweweeeeewwweeeeeeweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwewwwwwweeeeeeweeeeewwewwwwwwwwwweweeewewewwwewwwwewwweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwewewwwwwwewewewewewwewwwwwwwwwwwweeeewewwwwwweewwwweeweewwwwwwwwwwwwwwwwwwewwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwweeeeewwweweeeeeeeeeeeewwwwwwwwwweewewwwwwwweeewwwweewwweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwewewwweeewweweweweweweewwwwwwwwwwweewwwwwwwwwwwwweewwwwwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwweeeeeeeeweeeeeeeweweewewwwwwwwwwwwwwwwwwwwwwwwwwwwwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwewwewwewwwewewweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwweeeeeeeewwweeeeeweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwewwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwewwewwwwwwweweweweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwweeeewwwwwwweewewewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweeewwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwewwwwwwwwweeeewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweweeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwewwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwewweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewwwwwwwwwwweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweeeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwweeeewwewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweeeewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwweeewewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
"""
